-- ========================================================
-- SCRIPT: HISTORIAL DE CAMBIOS DE ESTADO (AUDITORÍA)
-- ========================================================
-- Este script crea un mecanismo automático para registrar
-- cada vez que un vehículo cambia su estado (operativo, demora, etc.)

-- 1. Asegurar que la tabla de estados actual tenga la columna updated_by
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name='gd_vehicle_status' AND column_name='updated_by') THEN
        ALTER TABLE gd_vehicle_status ADD COLUMN updated_by UUID REFERENCES auth.users(id);
    END IF;
END $$;

-- 2. Crear tabla de historial de estados
CREATE TABLE IF NOT EXISTS gd_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id UUID REFERENCES gd_vehicles(id) ON DELETE CASCADE,
    status TEXT NOT NULL,
    profile_id UUID REFERENCES auth.users(id),
    changed_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Habilitar RLS en la nueva tabla
ALTER TABLE gd_status_history ENABLE ROW LEVEL SECURITY;

-- 4. Política: Admins ven todo el historial
DROP POLICY IF EXISTS "Admins ven historial de estados" ON gd_status_history;
CREATE POLICY "Admins ven historial de estados" 
ON gd_status_history FOR SELECT 
TO authenticated 
USING (
  EXISTS (
    SELECT 1 FROM gd_profiles 
    WHERE id = auth.uid() 
    AND role_id = (SELECT id FROM gd_roles WHERE name = 'admin')
  )
);

-- 5. Función de Gatillo para capturar el cambio
CREATE OR REPLACE FUNCTION public.log_vehicle_status_change()
RETURNS TRIGGER AS $$
BEGIN
    -- Registramos si es una inserción nueva o si el estado cambió respecto al anterior
    IF (TG_OP = 'INSERT') OR (OLD.status IS DISTINCT FROM NEW.status) THEN
        INSERT INTO public.gd_status_history (vehicle_id, status, profile_id, changed_at)
        VALUES (NEW.vehicle_id, NEW.status, NEW.updated_by, now());
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. Trigger que dispara la función
DROP TRIGGER IF EXISTS tr_log_status_change ON gd_vehicle_status;
CREATE TRIGGER tr_log_status_change
    AFTER INSERT OR UPDATE ON gd_vehicle_status
    FOR EACH ROW EXECUTE PROCEDURE public.log_vehicle_status_change();

-- 7. Índices para reportes rápidos
CREATE INDEX IF NOT EXISTS idx_status_history_vehicle ON gd_status_history(vehicle_id, changed_at DESC);
