-- Función para actualizar el campo updated_at automáticamente
CREATE OR REPLACE FUNCTION gd_update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Tipos para los estados de los vehículos con prefijo
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gd_vehicle_status_type') THEN
        CREATE TYPE gd_vehicle_status_type AS ENUM ('operativo', 'demora', 'standby', 'mtto');
    END IF;
END $$;

-- Tabla de Vehículos con prefijo
CREATE TABLE IF NOT EXISTS gd_vehicles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patente TEXT UNIQUE NOT NULL,
    modelo TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

CREATE TRIGGER update_gd_vehicles_updated_at BEFORE UPDATE ON gd_vehicles FOR EACH ROW EXECUTE PROCEDURE gd_update_updated_at_column();

-- Tabla de Estado Actual y Ubicación con prefijo
CREATE TABLE IF NOT EXISTS gd_vehicle_status (
    vehicle_id UUID PRIMARY KEY REFERENCES gd_vehicles(id) ON DELETE CASCADE,
    status gd_vehicle_status_type DEFAULT 'standby',
    lat FLOAT8,
    lng FLOAT8,
    updated_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

CREATE TRIGGER update_gd_vehicle_status_updated_at BEFORE UPDATE ON gd_vehicle_status FOR EACH ROW EXECUTE PROCEDURE gd_update_updated_at_column();

-- Tabla de Historial de Estados con prefijo
CREATE TABLE IF NOT EXISTS gd_status_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id UUID REFERENCES gd_vehicles(id) ON DELETE CASCADE,
    status gd_vehicle_status_type NOT NULL,
    lat FLOAT8,
    lng FLOAT8,
    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

CREATE TRIGGER update_gd_status_logs_updated_at BEFORE UPDATE ON gd_status_logs FOR EACH ROW EXECUTE PROCEDURE gd_update_updated_at_column();

-- Habilitar Realtime para la tabla gd_vehicle_status
ALTER PUBLICATION supabase_realtime ADD TABLE gd_vehicle_status;

-- Tabla de Roles
CREATE TABLE IF NOT EXISTS gd_roles (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL, -- 'admin', 'driver', 'dispatcher'
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Insertar roles por defecto
INSERT INTO gd_roles (name, description) VALUES 
('admin', 'Administrador total del sistema'),
('driver', 'Chofer con acceso a reporte de GPS'),
('dispatcher', 'Despachador con acceso solo al mapa')
ON CONFLICT (name) DO NOTHING;

-- Tabla de Perfiles de Usuario
CREATE TABLE IF NOT EXISTS gd_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    role_id INTEGER REFERENCES gd_roles(id) DEFAULT (SELECT id FROM gd_roles WHERE name = 'driver'),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

CREATE TRIGGER update_gd_profiles_updated_at BEFORE UPDATE ON gd_profiles FOR EACH ROW EXECUTE PROCEDURE gd_update_updated_at_column();

-- Habilitar RLS para perfiles
ALTER TABLE gd_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow users to read their own profile" ON gd_profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Allow admins to read all profiles" ON gd_profiles FOR SELECT TO authenticated USING (
    EXISTS (
        SELECT 1 FROM gd_profiles p 
        JOIN gd_roles r ON p.role_id = r.id 
        WHERE p.id = auth.uid() AND r.name = 'admin'
    )
);

-- Trigger para crear perfil automáticamente al registrarse en Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.gd_profiles (id, email, full_name, role_id)
    VALUES (
        new.id, 
        new.email, 
        COALESCE(new.raw_user_meta_data->>'full_name', 'Nuevo Usuario'),
        (SELECT id FROM gd_roles WHERE name = 'driver') -- Por defecto todos son choferes
    );
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Eliminar el trigger si ya existe para evitar errores al re-ejecutar
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
