-- ========================================================
-- TABLA DE HISTORIAL GPS Y SEGURIDAD (v0.4.0)
-- ========================================================

-- 1. Crear la tabla de historial GPS
CREATE TABLE IF NOT EXISTS gd_gps_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id UUID REFERENCES gd_vehicles(id) ON DELETE CASCADE,
    profile_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    lat FLOAT8 NOT NULL,
    lng FLOAT8 NOT NULL,
    accuracy FLOAT8,
    captured_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Habilitar RLS
ALTER TABLE gd_gps_history ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de acceso
DROP POLICY IF EXISTS "Choferes insertan su GPS" ON gd_gps_history;
CREATE POLICY "Choferes insertan su GPS" 
ON gd_gps_history FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = profile_id);

DROP POLICY IF EXISTS "Admins ven todo el GPS" ON gd_gps_history;
CREATE POLICY "Admins ven todo el GPS" 
ON gd_gps_history FOR SELECT 
TO authenticated 
USING (
  EXISTS (
    SELECT 1 FROM gd_profiles 
    WHERE id = auth.uid() 
    AND role_id = (SELECT id FROM gd_roles WHERE name = 'admin')
  )
);

-- 4. Índices de optimización
CREATE INDEX IF NOT EXISTS idx_gps_history_vehicle_time ON gd_gps_history(vehicle_id, captured_at DESC);
